# Generated by Django 5.2.15 on 2026-06-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('team1_code', models.CharField(choices=[('ARG', 'Argentina'), ('BRA', 'Brazil'), ('FRA', 'France'), ('ENG', 'England'), ('GER', 'Germany'), ('ESP', 'Spain'), ('POR', 'Portugal'), ('NED', 'Netherlands'), ('ITA', 'Italy'), ('BEL', 'Belgium'), ('URU', 'Uruguay'), ('MEX', 'Mexico'), ('USA', 'United States'), ('CAN', 'Canada'), ('MAR', 'Morocco'), ('SEN', 'Senegal'), ('NGR', 'Nigeria'), ('GHA', 'Ghana'), ('JPN', 'Japan'), ('KOR', 'South Korea'), ('AUS', 'Australia'), ('IRN', 'Iran'), ('SAU', 'Saudi Arabia'), ('TBD', 'TBD')], default='TBD', max_length=10)),
                ('team2_code', models.CharField(choices=[('ARG', 'Argentina'), ('BRA', 'Brazil'), ('FRA', 'France'), ('ENG', 'England'), ('GER', 'Germany'), ('ESP', 'Spain'), ('POR', 'Portugal'), ('NED', 'Netherlands'), ('ITA', 'Italy'), ('BEL', 'Belgium'), ('URU', 'Uruguay'), ('MEX', 'Mexico'), ('USA', 'United States'), ('CAN', 'Canada'), ('MAR', 'Morocco'), ('SEN', 'Senegal'), ('NGR', 'Nigeria'), ('GHA', 'Ghana'), ('JPN', 'Japan'), ('KOR', 'South Korea'), ('AUS', 'Australia'), ('IRN', 'Iran'), ('SAU', 'Saudi Arabia'), ('TBD', 'TBD')], default='TBD', max_length=10)),
                ('team1_name', models.CharField(default='TBD', max_length=100)),
                ('team2_name', models.CharField(default='TBD', max_length=100)),
                ('group', models.CharField(blank=True, max_length=5)),
                ('stage', models.CharField(choices=[('GROUP', 'Group Stage'), ('R16', 'Round of 16'), ('QF', 'Quarterfinal'), ('SF', 'Semifinal'), ('THIRD', 'Third Place'), ('FINAL', 'Final')], default='GROUP', max_length=10)),
                ('date_bst', models.DateTimeField()),
                ('stadium', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed')], default='UPCOMING', max_length=15)),
                ('team1_score', models.IntegerField(blank=True, null=True)),
                ('team2_score', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_bst'],
            },
        ),
    ]
