# Generated by Django 5.2.15 on 2026-06-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1_code',
            field=models.CharField(choices=[('ARG', 'Argentina'), ('BRA', 'Brazil'), ('FRA', 'France'), ('ENG', 'England'), ('GER', 'Germany'), ('ESP', 'Spain'), ('POR', 'Portugal'), ('NED', 'Netherlands'), ('ITA', 'Italy'), ('BEL', 'Belgium'), ('URU', 'Uruguay'), ('MEX', 'Mexico'), ('USA', 'United States'), ('CAN', 'Canada'), ('MAR', 'Morocco'), ('SEN', 'Senegal'), ('NGR', 'Nigeria'), ('GHA', 'Ghana'), ('JPN', 'Japan'), ('KOR', 'South Korea'), ('AUS', 'Australia'), ('IRN', 'Iran'), ('SAU', 'Saudi Arabia'), ('TBD', 'TBD'), ('RSA', 'South Africa'), ('CZE', 'Czechia'), ('BIH', 'Bosnia and Herzegovina'), ('QAT', 'Qatar'), ('SUI', 'Switzerland'), ('HAI', 'Haiti'), ('SCO', 'Scotland'), ('PAR', 'Paraguay'), ('TUR', 'Türkiye'), ('CUW', 'Curaçao'), ('CIV', "Côte d'Ivoire"), ('ECU', 'Ecuador'), ('SWE', 'Sweden'), ('TUN', 'Tunisia'), ('EGY', 'Egypt'), ('NZL', 'New Zealand'), ('CPV', 'Cape Verde'), ('IRQ', 'Iraq'), ('NOR', 'Norway'), ('ALG', 'Algeria'), ('AUT', 'Austria'), ('JOR', 'Jordan'), ('COD', 'DR Congo'), ('UZB', 'Uzbekistan'), ('COL', 'Colombia'), ('CRO', 'Croatia'), ('PAN', 'Panama'), ('OTHER', 'Other')], default='TBD', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_code',
            field=models.CharField(choices=[('ARG', 'Argentina'), ('BRA', 'Brazil'), ('FRA', 'France'), ('ENG', 'England'), ('GER', 'Germany'), ('ESP', 'Spain'), ('POR', 'Portugal'), ('NED', 'Netherlands'), ('ITA', 'Italy'), ('BEL', 'Belgium'), ('URU', 'Uruguay'), ('MEX', 'Mexico'), ('USA', 'United States'), ('CAN', 'Canada'), ('MAR', 'Morocco'), ('SEN', 'Senegal'), ('NGR', 'Nigeria'), ('GHA', 'Ghana'), ('JPN', 'Japan'), ('KOR', 'South Korea'), ('AUS', 'Australia'), ('IRN', 'Iran'), ('SAU', 'Saudi Arabia'), ('TBD', 'TBD'), ('RSA', 'South Africa'), ('CZE', 'Czechia'), ('BIH', 'Bosnia and Herzegovina'), ('QAT', 'Qatar'), ('SUI', 'Switzerland'), ('HAI', 'Haiti'), ('SCO', 'Scotland'), ('PAR', 'Paraguay'), ('TUR', 'Türkiye'), ('CUW', 'Curaçao'), ('CIV', "Côte d'Ivoire"), ('ECU', 'Ecuador'), ('SWE', 'Sweden'), ('TUN', 'Tunisia'), ('EGY', 'Egypt'), ('NZL', 'New Zealand'), ('CPV', 'Cape Verde'), ('IRQ', 'Iraq'), ('NOR', 'Norway'), ('ALG', 'Algeria'), ('AUT', 'Austria'), ('JOR', 'Jordan'), ('COD', 'DR Congo'), ('UZB', 'Uzbekistan'), ('COL', 'Colombia'), ('CRO', 'Croatia'), ('PAN', 'Panama'), ('OTHER', 'Other')], default='TBD', max_length=10),
        ),
    ]
