# Generated by Django 5.2.15 on 2026-06-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_team1_code_alter_match_team2_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('GROUP', 'Group Stage'), ('R32', 'Round of 32'), ('R16', 'Round of 16'), ('QF', 'Quarterfinal'), ('SF', 'Semifinal'), ('THIRD', 'Third Place'), ('FINAL', 'Final')], default='GROUP', max_length=10),
        ),
    ]
