# Generated by Django 5.2.15 on 2026-06-09 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('entry_type', models.CharField(choices=[('FREE', 'Free Entry'), ('PAID', 'Paid Entry'), ('DONATION', 'Donation')], default='FREE', max_length=10)),
                ('entry_fee_details', models.CharField(blank=True, max_length=200)),
                ('screen_size', models.CharField(choices=[('TV', 'Small TV'), ('BIG', 'Big Screen'), ('PROJECTOR', 'Full Projector')], default='BIG', max_length=15)),
                ('crowd_capacity', models.CharField(choices=[('SMALL', 'Small (< 20)'), ('MEDIUM', 'Medium (20–100)'), ('LARGE', 'Large (100+)')], default='MEDIUM', max_length=10)),
                ('contact_info', models.CharField(blank=True, max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='venues/')),
                ('verified', models.BooleanField(default=False)),
                ('community_rating', models.FloatField(default=0.0)),
                ('rating_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VenueMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_matches', to='matches.match')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_matches', to='venues.watchvenue')),
            ],
            options={
                'unique_together': {('venue', 'match')},
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
                ('venue_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_set', to='venues.venuematch')),
            ],
            options={
                'unique_together': {('user', 'venue_match')},
            },
        ),
        migrations.CreateModel(
            name='VenueRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='venues.watchvenue')),
            ],
            options={
                'unique_together': {('user', 'venue')},
            },
        ),
    ]
