# Generated by Django 5.2.15 on 2026-06-09 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supported_team', models.CharField(choices=[('ARG', 'Argentina'), ('BRA', 'Brazil'), ('FRA', 'France'), ('ENG', 'England'), ('GER', 'Germany'), ('ESP', 'Spain'), ('POR', 'Portugal'), ('NED', 'Netherlands'), ('ITA', 'Italy'), ('BEL', 'Belgium'), ('URU', 'Uruguay'), ('MEX', 'Mexico'), ('USA', 'United States'), ('CAN', 'Canada'), ('MAR', 'Morocco'), ('SEN', 'Senegal'), ('NGR', 'Nigeria'), ('GHA', 'Ghana'), ('JPN', 'Japan'), ('KOR', 'South Korea'), ('AUS', 'Australia'), ('IRN', 'Iran'), ('SAU', 'Saudi Arabia'), ('OTHER', 'Other')], default='ARG', max_length=10)),
                ('fan_score', models.IntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
